name: "Create trading signals vpc + db"
on:
  push:
    branches:
      - main
jobs:
  terraform:
    name: "Trading Signals Basic Resources"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      STATE_BUCKET_KEY: ${{ secrets.STATE_KEY }}
      STATE_BUCKET: ${{ secrets.STATE }}
      TF_VAR_region: ${{ secrets.AWS_REGION }}
      TF_VAR_dbname: ${{ secrets.DBNAME }}
      TF_VAR_dbuser: ${{ secrets.DBUSER }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_KEY }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=$STATE_BUCKET_KEY" -backend-config="bucket=$STATE_BUCKET" -backend-config="region=$TF_VAR_region"

      - name: code format
        id: fmt
        run: terraform fmt -check

      - name: Execute Plan
        id: plan
        run: terraform plan -no-color -var-file=prod.tfvars > /dev/null
        continue-on-error: true

      - name: Exit on Plan Failure
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Apply Changes
        run: terraform apply -auto-approve -var-file=prod.tfvars > /dev/null
